### ISSUE TITLE
How can I sync same index, but different type...?

### ISSUE THREAD

**Issue by perfectacle** [siddontang/go-mysql-elasticsearch#162]
if...
database name: test
table name: student, teacher, company, school, ...

go-mysql-elasticsearch works like below...
index name: student
type name: student

index name: teacher
type name: teacher

index name: company
type name: company
...

but I want below...
index name: test
type name: student, teacher, company, school, ....

How can I...??

Do I have to write a rule for every table?

**Comment by siddontang** [comment]
you can see https://github.com/siddontang/go-mysql-elasticsearch/blob/master/river/rule.go#L30 and pass a config like MapSchemaToIndex to support this - using the schema as the index and the table as the type by default.

But I don't think it is a common case because you must ensure all your table have the same type.

**Comment by perfectacle** [comment]
Thanks siddontang!
