### ISSUE TITLE
wildcard for schema name

### ISSUE THREAD

**Issue by alexzR0me** [siddontang/go-mysql-elasticsearch#199]

**Comment by siddontang** [comment]
hi @alexzR0me 

Now we only support wildcard for the table, if you want to use the wildcard for the database, we must ensure the table with the same name in different databases must have the same schema.

Meanwhile, we can't support DDL like `alter table` because we have to change tables one by one, this may cause sync failed later. (Although we don't support DDL too, we will support it later :-) )

**Comment by IronSinew** [comment]
@siddontang So if you have a multi-tenanted, distributed schema that is consistent across multiple schemas, how would you currently support that? To use Alex's example, of all `abx-*` schemas did have the same tables, is that possible currently?
